Produkt_Details_Screen As screen:
    Fill: =RGBA(128, 128, 128, 1)

    Label3 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =66
        Size: =21
        Text: =Var_Produkt.Title
        Width: =336
        X: =50
        Y: =566
        ZIndex: =1

    Rectangle1_14 As rectangle:
        Fill: =RGBA(0, 0, 0, 1)
        Height: =137
        TabIndex: =
        Width: =639
        ZIndex: =2

    Label1_8 As label:
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.'Courier New'
        FontWeight: =FontWeight.Bold
        Height: =100
        Italic: =true
        Size: =45
        Text: |-
            ="Durchstöbern
            "
        Width: =457
        X: =50
        Y: =20
        ZIndex: =3

    Icon1_7 As icon.ShoppingCart:
        Color: =RGBA(255, 255, 255, 1)
        Height: =100
        Icon: =Icon.ShoppingCart
        OnSelect: =Navigate(Einkaufswagen_Screen)
        Width: =100
        X: =518
        Y: =20
        ZIndex: =4

    Image4 As image:
        Height: =357
        Image: =Var_Produkt.ProduktBild
        Width: =412
        X: =50
        Y: =224
        ZIndex: =5

    Label6 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =235
        Size: =21
        Text: =Var_Produkt.Beschreibung
        Width: =548
        X: =50
        Y: =783
        ZIndex: =6

    Label7 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =70
        Size: =21
        Text: |-
            ="Bescheibung:"
        Underline: =true
        Width: =560
        X: =50
        Y: =739
        ZIndex: =7

    Button2 As button:
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(153, 153, 153, 1)
        Height: =56
        OnSelect: =Navigate(Suche_Screen)
        Size: =24
        Text: ="Zurück"
        Width: =190
        Y: =137
        ZIndex: =8

    Label9 As label:
        Color: =RGBA(255, 255, 255, 1)
        Fill: =RGBA(128, 128, 128, 1)
        FontWeight: =FontWeight.Bold
        Height: =60
        Size: =23
        Text: =Var_Produkt.Preis & "€"
        Width: =360
        X: =50
        Y: =655
        ZIndex: =9

    Star2 As star:
        BorderColor: =RGBA(255, 255, 0, 1)
        BorderThickness: =1
        Fill: |-
            =If(
                IsBlank(
                    LookUp(Filter(HardwareLord_Favoriten, Title = Var_UserID), Produkt_ID = Var_Produkt.ID)
                ),
                RGBA(255,255,255,1),
                RGBA(255,215,0,1)
            )
        OnSelect: |-
            =If(
                IsBlank(
                    LookUp(Filter(HardwareLord_Favoriten, Title = Var_UserID), Produkt_ID = Var_Produkt.ID)
                ),
                Collect(HardwareLord_Favoriten, {Title:Text(Var_UserID), Produkt_ID:Var_Produkt.ID}),
                Remove(HardwareLord_Favoriten, LookUp(Filter(HardwareLord_Favoriten, Title = Var_UserID), Produkt_ID = Var_Produkt.ID))
            )
        X: =518
        Y: =150
        ZIndex: =10

    Rectangle1_15 As rectangle:
        Fill: =RGBA(0, 0, 0, 1)
        Height: =137
        Width: =639
        X: =1
        Y: =994
        ZIndex: =11

    Icon3_6 As icon.Home:
        BorderColor: =RGBA(0, 0, 0, 0)
        Color: =RGBA(255, 255, 255, 1)
        Height: =100
        Icon: =Icon.Home
        OnSelect: =Navigate(Home_Screen)
        Width: =100
        X: =30
        Y: =995
        ZIndex: =12

    Label2_25 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Height: =25
        Size: =20
        Text: |-
            ="Home
            "
        Width: =100
        X: =30
        Y: =1100
        ZIndex: =13

    Icon2_6 As icon.Search:
        Color: =RGBA(255, 255, 255, 1)
        Height: =100
        Icon: =Icon.Search
        OnSelect: =Navigate(Suche_Screen)
        Width: =100
        X: =190
        Y: =995
        ZIndex: =14

    Label2_26 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Height: =25
        Size: =20
        Text: |-
            ="Suche
            "
        Width: =100
        X: =190
        Y: =1100
        ZIndex: =15

    Star1_6 As star:
        BorderColor: =RGBA(255, 255, 255, 1)
        BorderThickness: =6
        Fill: =RGBA(0, 0, 0, 0)
        Height: =80
        OnSelect: =Navigate(Favoriten_Screen)
        Width: =80
        X: =360
        Y: =1005
        ZIndex: =16

    Label2_27 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Height: =36
        Size: =20
        Text: |-
            ="Favoriten
            "
        Width: =132
        X: =335
        Y: =1095
        ZIndex: =17

    Icon4_6 As icon.Person:
        Color: =RGBA(255, 255, 255, 1)
        Height: =100
        Icon: =Icon.Person
        OnSelect: =Navigate(Konto_Screen)
        Width: =100
        X: =510
        Y: =995
        ZIndex: =18

    Label2_28 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Height: =25
        Size: =20
        Text: |-
            ="Konto
            "
        Width: =100
        X: =510
        Y: =1100
        ZIndex: =19

